### ISSUE TITLE
Colourful highlighting of anaphors doesn't work

### ISSUE THREAD

**Issue by SergeyMikhaylov21** [amir-zeldes/xrenner#63]
I wrote some very simple rules, but highlighting of anaphors doesn't work. 
I worked with russian language and my config.ini is the same as @ftyers has. 
Here is a link on a screenshot of my output: https://yadi.sk/i/70yGbvBv3Q39Wf

Here is my rules in coref_rules.tab:
`lemma="кое-кто";lemma="посетитель";0;propagate`
`entity="person";entity="person"&text=$1;1;nopropagate`
`form="pronoun";form="proper";1;nopropagate`

changing 0 to 1 (and back) doesn't help :(

System is Win 8.1.

**Comment by amir-zeldes** [comment]
Hi @SergeyMikhaylov21 , it's difficult to be sure without seeing the full model and input data. Since the markables show up correctly, I'm guessing this isn't a visualization problem but really the system doesn't think those mentions are coreferent (you can check in the HTML source code whether they have the same group ID).

Assuming they are not flagged as coreferent in the analysis, many things could be causing this. Are you requiring that only definites can have antecedents in config.ini? That would probably be bad for Slavic languages. Is the lemma посетитель correctly recognized for the actual form посетители? Is there number agreement information that rules out the match (sg/pl)? 

I'm also noticing that "кое-кто" is flagged as a common noun instead of a pronoun. This seems wrong, no? If it's really a common noun, then the rule above is not sufficient for coreference: common nouns with different lemmas are never coreferent unless there is some kind of semantic relationship between them, either listed in coref.tab, or more flexibly using the 'is-a' mechanism in isa.tab. If you want morphologically unrelated nouns to corefer, you should read those files. Alternatively, consider making кое-кто a pronoun (POS tag and in pronouns.tab). 

Does any of those ideas fix the issue?

**Comment by SergeyMikhaylov21** [comment]
Yeah, it helped, thanks a lot!

**Comment by ftyers** [comment]
@SergeyMikhaylov21 could you let us know what helped ? e.g. what does "it" in your message refer to ? :D
