### ISSUE TITLE
No module named 'modules'

### ISSUE THREAD

**Issue by VarvaraHuts** [amir-zeldes/xrenner#64]
Hi! I'm quite new to coding, and I do not understand why I can't install xrenner. 

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-a4fd832a4193> in <module>()
----> 1 import xrenner

C:\Users\ponch\Anaconda3\lib\site-packages\xrenner-1.4.1.8-py3.6.egg\xrenner\__init__.py in <module>()
      1 ## xrenner init ##
----> 2 from modules.xrenner_xrenner import Xrenner

ModuleNotFoundError: No module named 'modules'

**Comment by amir-zeldes** [comment]
This looks like a Python 3 compatibility issue. I think it might already be solved in the `develop` branch, but not in the stable release. Can you try switching the branch from 'master' to 'develop' on the main github page, then downloading the repo, unzipping and running xrenner in that directory? Alternatively you can also use Python 2.7 instead of 3.6.

**Comment by amir-zeldes** [comment]
Resolved in V2.X+ as of af17ae8b2f4bc378eea7105cd82b3609d17f2b02
