### ISSUE TITLE
override.ini is not optional

### ISSUE THREAD

**Issue by asharkinasuit** [amir-zeldes/xrenner#75]
The file is used (now) to specify that no classifiers should be used when running the test suite, at least in the English model, so it probably shouldn't be optional (or it should be hardcoded into the test setup somehow, but that looks like it could be dirty).

**Comment by amir-zeldes** [comment]
This is a good point, thanks for spotting it! I wasn't initially concerned about this since the test option is hardwired to run on the English model, which is provided with the distribution. But it's definitely not clean, and a user could decide to overwrite the English model and do something new. Then again, the user could completely alter model settings and cause tests to fail that way, regardless of override.ini.

I think actually hardwiring the behavior inside the test module might make the most sense. I would have added a hidden clone of the whole model used for 'test', but I don't want to inflate the distribution size with copies of the lexical data. I'll think about this a little more.

**Comment by asharkinasuit** [comment]
Yea, right now I've simply copied the English test cases for my model and translated them, then updated the hardcoded references to the test module to point to my copy, but indeed to make it more general may require some thought.
I was thinking for starters you might still parse the arguments if -t is included and that way enable people to give both the model to test using -m and the test harness to use (perhaps as a string belonging to -t).

**Comment by amir-zeldes** [comment]
It seems the override file is no longer required, but for the test you really need to have the provided model anyway (otherwise tests will fail too). Closing this for now.
