### ISSUE TITLE
First name agreement is not resolved

### ISSUE THREAD

**Issue by asharkinasuit** [amir-zeldes/xrenner#76]
I'm not entirely sure this is really a bug, but while tinkering with the appos_envelope test, I ran into the following issue.
Suppose `names.tab` contains a full name and with a gender, say `John Smith\tM`. Now, if a markable John Namedoesntoccurinthelistofnames is encountered, this name is not inferred to be male even though the first name John is known to be male (by `lex.first_names['John']`). I would imagine this is a missing case in the conditional statement at `xrenner_marker.py:424`. Specifically, it seems line 427 assumes that such a name would have been split up, in which case John would indeed be recognized. I did notice that kind of long surname results in two markables, `John` and the full one, but at least in the appos_envelope test the correct chain is not made...
I guess there will be androgynous names for which this heuristic could lead to the wrong agreement class being inferred, but is that more common than failing to recognize any agreement class because the last name is unknown? Or am I failing to see something else that's causing the chain to break?

edit: I'm more confused now because after trying the test with the following added, it still fails the same way:
```
...
427: elif mark.core_text in lex.first_names:  # Single name component core text
	return [lex.first_names[mark.core_text]]
>>>
elif mark.core_text.split(' ')[0] in lex.first_names:
	return [lex.first_names[mark.core_text.split(' ')[0]]]
<<<
...
```

**Comment by amir-zeldes** [comment]
Hi and thanks again for looking into this! I remember this issue, so while I can't say you're wrong, I CAN say it's not an accident...

The thing to understand about `names.tab` is that although it offers complete first+last names, actually the program generates all first + last combinations from that list, so that first-name logic is applied to anything that is perceived as a conceivable first + last (even if unattested as a specific full name in `names.tab`). 

I remember trying to play around with this and being more lax about first names based on some examples where it would have worked, but on the whole, it had adverse effects. The reason is that, if something looks like `first + ????`, and has the appropriate syntactic dependency (in SD, `nn`, in UD `flat`), it is very much not necessarily a person name, since very many first names are homophones of common nouns or non persons (River in River Phoenix, or Wolf Blitzer). We want to make sure that 'Wolf Stockade' is not coreferent with 'Wolf' based on an imagined reading as a first + [unknown last name].'

Does that make sense? I guess we could parametrize this, or rely on the ML to sort the right from wrong, but it seemed risky on a semantic level. Maybe there should be a way of dynamically inserting things into the last names based on evidence, similar to dynamic hasa matching.

**Comment by amir-zeldes** [comment]
BTW the quickest solution is to add the missing last name to names.tab (you may need a well curated list of Dutch names missing from the list for example)

**Comment by asharkinasuit** [comment]
Thank you, that does make a lot of sense, of course there could be any number of things a potential first name is applied to where the next bit isn't the surname...
